# Generated by Django 4.2 on 2023-05-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0003_reviews_timestamp_tickets_timestamp"),
    ]

    operations = [
        migrations.RemoveField(model_name="movies", name="hall",),
        migrations.AddField(
            model_name="reviews",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_review",
                to="ticket_purchase.movies",
            ),
            preserve_default=False,
        ),
    ]
