# Generated by Django 4.2 on 2023-05-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0005_alter_reviews_author_movie_hall_allocation"),
    ]

    operations = [
        migrations.DeleteModel(name="Movie_Hall_Allocation",),
    ]
