# Generated by Django 4.2 on 2023-05-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0006_delete_movie_hall_allocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie_Hall_Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_info", models.DateTimeField()),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_purchase.halls",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_purchase.movies",
                    ),
                ),
            ],
        ),
    ]
