# Generated by Django 4.2 on 2023-06-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0007_movie_hall_allocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickets", old_name="seat_num", new_name="seat_column",
        ),
    ]
