# Generated by Django 4.2 on 2023-06-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0008_rename_seat_num_tickets_seat_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="movie_hall_allocation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket",
                to="ticket_purchase.movie_hall_allocation",
            ),
            preserve_default=False,
        ),
    ]
