# Generated by Django 4.2 on 2023-06-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0009_tickets_movie_hall_allocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickets", old_name="movie_hall_allocation", new_name="session",
        ),
    ]
