# Generated by Django 4.2 on 2023-06-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0010_rename_movie_hall_allocation_tickets_session"),
    ]

    operations = [
        migrations.RemoveField(model_name="tickets", name="movie",),
    ]
