# Generated by Django 4.2 on 2023-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0013_alter_tickets_timestamp_alter_transaction_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner", models.ImageField(upload_to="banners/")),
            ],
        ),
    ]
