# Generated by Django 4.2 on 2023-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0014_highlights"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlights",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
