# Generated by Django 4.2 on 2023-06-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_purchase", "0015_highlights_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="cast",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="genre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="release",
            field=models.DateField(blank=True, null=True),
        ),
    ]
